### ISSUE TITLE
`--` as an argument delimiter doesn't work correctly in commands

### ISSUE THREAD

**Issue by samth** [racket/raco-cross#11]
`raco cross test -l typed-racket-test -- --all` should work like `raco test -l typed-racket-test -- --all` but instead `--` is incorrectly parsed as a collection name.

**Comment by mflatt** [comment]
I think `--` is parsed as a collection name with `raco test`, too:

```
laptop$ raco test -l typed-racket-test -- --all
raco test: (submod (file "/Users/mflatt/plt/extra-pkgs/typed-racket/typed-racket-test/main.rkt") test)
raco test: @(test-responsible '(samth stamourv endobson "drdr@syntaxforge.net"))
standard-module-name-resolver: collection not found
  for module path: (lib "--")
  collection: "--"
```

Maybe the confusion is that `-l` doesn't work in `raco test` like it works in some other places.

**Comment by samth** [comment]
Sorry, this was an error on my part.
