### ISSUE TITLE
Binary built on Linux for Windows gives linklet contract violation

### ISSUE THREAD

**Issue by sschwarzer** [racket/raco-cross#2]
Finally, I had a chance to test a binary cross-compiled on Linux (host) for Windows (target). The binary is supposed to be a standalone binary, i. e. with all dependencies included to run under Windows.

When running the binary, I get:
```
C:\Users\...\Downloads>sudoku-solver-x86_64-windows.exe --help
instantiate-linklet: contract violation
  expected: linklet?
  given: #<correlated-linklet>
```

The build log is at
https://builds.sr.ht/~sschwarzer/job/531096
starting for the Windows build at
https://builds.sr.ht/~sschwarzer/job/531096#task-build-all-170

The cross-compilation itself is done with
```
raco cross --target "x86_64-win32" --vm cs -j 4 exe --orig-exe --embed-dlls \
	-o "build/x86_64-windows/sudoku-solver-x86_64-windows" games/sudoku-solver.rkt
```
(`raco-cross` is installed with installation scope) and results in this binary:
https://patchouli.sr.ht/builds.sr.ht/artifacts/~sschwarzer/531096/12b4f3e2df65899d/sudoku-solver-x86_64-windows.exe

In case it's relevant, the Makefile I use for building is at
https://git.sr.ht/~sschwarzer/sudoku-solver/tree/main/item/Makefile

**Comment by mflatt** [comment]
This looks like the problem with v8.1 Racket CS where cross-building does not work. That problem is fixed for the upcoming v8.2 release.

**Comment by sschwarzer** [comment]
Thanks a lot! :-)

**Comment by mflatt** [comment]
Closing now that v8.2 is out.

**Comment by sschwarzer** [comment]
I was going to suggest to close the ticket. I tried out the Windows binary compiled with Racket 8.2 today and it works now. I'm very happy! :-)
