### ISSUE TITLE
rumble exception during `raco setup`

### ISSUE THREAD

**Issue by Bogdanp** [racket/raco-cross#6]
I wasn't sure whether or not to report this in the main Racket repo or here. I chose to report it here because the problem doesn't occur when I run `raco setup` using the same Racket version on Linux.

When I run

```
$ raco cross --target x86_64-linux pkg install a-package/
```

I see several exceptions like this during `setup`:

```
Exception: invalid bound variable #[#{literal-placeholder kbkqt2cjt71krl4k849g6n05s-14} 0] in (let ((#[...] (...))) #[#{literal-placeholder kbkqt2cjt71krl4k849g6n05s-14} 0]) near line 972, char 22 of rumble/procedure.ss
```

and the process eventually hangs.

```
>> Cross configuration
 Target:    x86_64-linux
 Host:      x86_64-macosx
 Version:   8.3
 VM:        cs
 Workspace: /Users/bogdan/Library/Racket/raco-cross/8.3
```

**Comment by mflatt** [comment]
I haven't been able to replicate this, but it looks like your cross installation (likely the generated cross compiler for x86_64-linux) has gone wrong somehow.

Have you been using `raco cross` successfully, so that it's something about this specific pattern of `pkg install`? Or is this an initial exploration and most anything you try goes wrong?

Does the same thing happen if you specify a fresh workspace with `--workspace` (instead of using "/Users/bogdan/Library/Racket/raco-cross/8.3") or if you move "/Users/bogdan/Library/Racket/raco-cross/8.3" to a different path so that `raco cross` recreates it?

**Comment by Bogdanp** [comment]
Thanks for taking a look! The problem is specific to installing a particular app/package, and using a fresh workspace doesn't fix it. I've used `raco cross` successfully before, but never with as complex an application. The repo for this application isn't public, but I can grant you access if you think that would help. If not, I can dig in some more this weekend.

**Comment by mflatt** [comment]
Ok, that makes sense. Refreshing my memory on `literal-placeholder`, I see that it's specific to cross compilation, so this is probably a straightforward bug in the communication channel for cross compilation. Using `raco cross ... make`, you might be able to narrow down the problem to a specific example module, or I'd be happy to take a look if you want to grant access.

**Comment by Bogdanp** [comment]
Here is a minimal example that reproduces the issue:

```racket
#lang racket/base

(require (for-syntax racket/base))

(define-syntax (example stx)
  (syntax-case stx ()
    [(_)
     (with-syntax ([constructor-id (gensym)])
       #'(struct example ()
           #:constructor-name constructor-id
           #:transparent))]))

(example)
```

Running

```
raco cross --target x86_64-linux make test.rkt
```

results in:

```
>> Cross configuration
 Target:    x86_64-linux
 Host:      x86_64-macosx
 Version:   8.3
 VM:        cs
 Workspace: /Users/bogdan/work/blackmagic/ws
"/Users/bogdan/tmp/test.rkt":
  making #<path:/Users/bogdan/tmp/test.rkt>
Exception: invalid bound variable #[#{literal-placeholder c8z5adwvcw0jwysxzhrznagsm-14} 0] in (let ((#[...] (...))) #[#{literal-placeholder c8z5adwvcw0jwysxzhrznagsm-14} 0]) near line 972, char 22 of rumble/procedure.ss
integer-bytes->integer: contract violation
  expected: bytes?
  given: #<eof>
```

**Comment by mflatt** [comment]
Thanks for the example! Here's an even smaller one:

```
#lang racket/base
(require (for-syntax racket/base))

(define-syntax (example stx)
  (with-syntax ([id (gensym)])
    #`(let ([id (lambda (x) 'id)])
        id)))

(example)
```

The problem case is when an uninterned symbol is used both under a quote and as the inferred name a procedure.

**Comment by mflatt** [comment]
This commit is meant to fix the problem: https://github.com/racket/racket/commit/aec41f37805fd8c0f4e3515ea802487dcb5fc5b5

**Comment by Bogdanp** [comment]
I just tried it using the latest snapshot, and it looks like that did the trick. Thanks!
